name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --verbosity normal
    - name: Pack
      run: dotnet pack ItemChanger/ItemChanger.csproj -o nuget/
    - name: Get Version
      id: version
      run: |-
        VERSION=$(dotnet build ItemChanger/ItemChanger.csproj -getProperty:PackageVersion)
        echo Version is $VERSION
        echo "version=$VERSION" >> $GITHUB_OUTPUT
