name: Docs

on:
  push:
    branches: [ main ]

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        
      - name: Setup DocFX
        run: dotnet tool update -g docfx
      
      - name: DocFX build
        working-directory: docs
        run: docfx
        continue-on-error: false

      - name: Upload assets
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/_site

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
